### ISSUE TITLE
Switching to netstandard2.0 ?

### ISSUE THREAD

**Issue by AKEOPLUS-boris-bocquet** [denikson/zerorpc-dotnet#6]
Hi Denikson, 

do you expect to upgrade this project to dotnet standard (e.g. netstandard2.0) ? This is "the future" (the trend) and it is better for durability and portability (i.e. on Linux). I did a small trial and it worked well : just changed some project parameters and change the dependencies (AsyncIO, MsgPack.Cli, NetMQ) to use the one with dotnet standard. 

Best Regards

Boris

**Comment by ghorsington** [comment]
Greetings!

You can indeed run zerorpc-dotnet on much newer versions of .NET. Originally I made this port because I needed to use zerorpc with Unity -- hence such low framework version.

Feel free to make a fork (or a hardclone) of this project and migrate to Core/NetStandard. I will not merge the changes unless you preserve compilability under 3.5.

If you do want to make a proper migration, I'd suggest changing some parts of the code. Mainly 

* Use netmq pollers and queues for message handling. I wasn't able to use those because of older framework version.
* Replace BeginInvokes with async. Currently there is an overhead for using thread pools. You can get away with much less background threads by processing messages via async. That way you can also get nice Invoke overloads for the client that use async as well.

**Comment by AKEOPLUS-boris-bocquet** [comment]
Dear Denikson, 
these are some precises advices, from the wised C# developper you are. The current code works perfectly with Core/NetStandard without any additional sweat. Your proposal might represent some workload (maybe I am exagerating, but I don't know 0mq very well). Are the advantages worthing the effort? Are you thinking about more developments on this project with framework <= 3.5 ? Or are your developments finished (or close to the end)?

**Comment by ghorsington** [comment]
The advantages really depend on the purpose you're using zerorpc for. If what you are doing is speed- and space-critical, upgrading the code not only will make it more clear, but should also provide some performance boost. As I vaguely mentioned, it's better to manage thread count manually -- right now I have no power over how many threads RPC runs on without going an extra mile to implement a custom event dispatcher.

As for further development, I currently don't plan on adding/changing anything besides fixing possible bugs. I initially made this port for a special RPC between a UI and a Unity game, but I have since moved to use Windows named pipes instead of zerorpc.

**Comment by AKEOPLUS-boris-bocquet** [comment]
Dear Denikson, 
thanks for the complements. I discussed with some colleagues and thought that we will keep it as is and just change the dependancies on our local version. At least for today. We keep your ideas and proposal in mind for a potential upgrade, one of the days (but not sure). Again, I thank you for your codes and your posts. 
Cheers.
